import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import { useState } from 'react';
import { useCryptoAssets } from '../../hooks/useCryptoAssets';
import { Download, FileJson, FileSpreadsheet } from 'lucide-react';

export default function ReportsPage() {
  const { rawAssets } = useCryptoAssets();
  const [generating, setGenerating] = useState('');
  const [reportMessage, setReportMessage] = useState('');

  const runReport = (type, generator) => {
    if (generating) return;
    setGenerating(type);
    setReportMessage('');
    window.setTimeout(() => {
      generator();
      setGenerating('');
      setReportMessage(`${type === 'cbom' ? 'CBOM JSON' : type === 'csv' ? 'Inventory CSV' : 'Executive report'} generated and download started.`);
    }, 650);
  };

  const handleDownloadJSON = () => {
    const cbom = {
      bomFormat: 'CycloneDX',
      specVersion: '1.6',
      serialNumber: 'urn:uuid:ecdat-cbom-enterprise-perimeter',
      version: 1,
      metadata: {
        timestamp: new Date().toISOString(),
        tools: [{ vendor: 'ECDAT', name: 'Enterprise Cryptographic Discovery Tool', version: '1.0.0' }],
        component: { name: 'Enterprise Core Perimeter', type: 'application' }
      },
      cryptographicAssets: rawAssets
    };
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(cbom, null, 2));
    const dl = document.createElement('a');
    dl.setAttribute('href', dataStr);
    dl.setAttribute('download', 'enterprise_cbom_cyclonedx_1.6.json');
    document.body.appendChild(dl);
    dl.click();
    document.body.removeChild(dl);
  };

  const handleDownloadCSV = () => {
    const headers = ['Asset ID', 'Algorithm', 'Purpose', 'Application', 'Risk Band', 'Quantum Status'];
    const rows = rawAssets.map(a => [
      a.id,
      a.algorithm?.name || 'N/A',
      a.usage?.purpose || 'N/A',
      a.context?.applicationName || 'N/A',
      a.riskBand || 'N/A',
      a.status?.quantum || 'N/A'
    ]);
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', 'ecdat_inventory_export.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExecutiveReport = () => {
    const vulnerable = rawAssets.filter((asset) => asset.status?.quantum === 'vulnerable').length;
    const critical = rawAssets.filter((asset) => asset.riskBand === 'critical').length;
    const pqcReady = rawAssets.filter((asset) => asset.status?.quantum === 'pqc_native').length;
    const report = [
      'ECDAT — EXECUTIVE QUANTUM RISK BRIEF',
      `Generated: ${new Date().toLocaleString()}`,
      '',
      'POSTURE SUMMARY',
      `Total cryptographic assets: ${rawAssets.length}`,
      `Quantum-vulnerable assets: ${vulnerable}`,
      `Critical-risk findings: ${critical}`,
      `PQC-native assets: ${pqcReady}`,
      '',
      'RECOMMENDED NEXT STEPS',
      '1. Prioritize internet-facing and critical-risk assets for migration planning.',
      '2. Validate hybrid ML-KEM and ML-DSA compatibility in staging environments.',
      '3. Track remediation progress against the organization\'s Mosca timing assumptions.',
      '',
      'Generated by ECDAT Enterprise Cryptographic Discovery & Analysis Tool.'
    ].join('\n');
    const link = document.createElement('a');
    link.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent(report);
    link.download = 'ecdat_executive_quantum_risk_brief.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      <PageHeader
        title="Compliance & Audit Reports"
        subtitle="Export standardized Cryptographic Bill of Materials (CBOM), executive risk briefs, and audit logs"
      />

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
        {/* CBOM CycloneDX Export Card */}
        <Card title="CycloneDX 1.6 CBOM Export" subtitle="Standardized machine-readable cryptographic catalog">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Badge variant="pqc">CYCLONEDX 1.6</Badge>
              <Badge variant="info">JSON FORMAT</Badge>
            </div>
            <p style={{ fontSize: '13px', color: '#475569', lineHeight: 1.5, margin: 0 }}>
              Complete machine-readable export following the OWASP CycloneDX Cryptography Extension specification, detailing algorithms, key lengths, certificates, and detection evidence.
            </p>
            <div style={{ paddingTop: '8px' }}>
              <Button variant="primary" icon={FileJson} onClick={() => runReport('cbom', handleDownloadJSON)} disabled={Boolean(generating)} aria-busy={generating === 'cbom'}>
                {generating === 'cbom' ? 'Preparing CBOM...' : 'Download CBOM JSON'}
              </Button>
            </div>
          </div>
        </Card>

        {/* Inventory Spreadsheet Export */}
        <Card title="Cryptographic Perimeter Spreadsheet" subtitle="Comma-separated tabular inventory for audit teams">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Badge variant="success">CSV FORMAT</Badge>
              <Badge variant="default">1,284 ASSETS</Badge>
            </div>
            <p style={{ fontSize: '13px', color: '#475569', lineHeight: 1.5, margin: 0 }}>
              High-level tabular snapshot containing asset IDs, owning applications, classical and quantum risk classifications, and designated migration runways.
            </p>
            <div style={{ paddingTop: '8px' }}>
              <Button variant="secondary" icon={FileSpreadsheet} onClick={() => runReport('csv', handleDownloadCSV)} disabled={Boolean(generating)} aria-busy={generating === 'csv'}>
                {generating === 'csv' ? 'Preparing CSV...' : 'Download Inventory CSV'}
              </Button>
            </div>
          </div>
        </Card>

        {/* Executive Risk Brief */}
        <Card title="Executive Quantum Risk Brief" subtitle="Board-level executive summary of PQC readiness">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Badge variant="critical">EXECUTIVE AUDIT</Badge>
              <Badge variant="info">NIST COMPLIANCE</Badge>
            </div>
            <p style={{ fontSize: '13px', color: '#475569', lineHeight: 1.5, margin: 0 }}>
              Summarizes the estimated 2034 threat horizon, Mosca theorem deficits across core banking, and active migration progress for compliance officers.
            </p>
            <div style={{ paddingTop: '8px' }}>
              <Button variant="outline" icon={Download} onClick={() => runReport('executive', handleExecutiveReport)} disabled={Boolean(generating)} aria-busy={generating === 'executive'}>
                {generating === 'executive' ? 'Generating brief...' : 'Generate Executive Report'}
              </Button>
            </div>
          </div>
        </Card>
      </div>
      {generating && <div className="report-generation-toast" role="status" aria-live="polite"><span className="report-spinner" /> Building your {generating === 'cbom' ? 'CycloneDX CBOM' : generating === 'csv' ? 'inventory export' : 'executive risk brief'}...</div>}
      {reportMessage && !generating && <div className="report-success-toast" role="status" aria-live="polite">✓ {reportMessage}</div>}
    </div>
  );
}
